// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace BaseGameplayTags
{
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reload);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Firing);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reloading);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_OutOfAmmo);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);

	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crouch);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Airborne);

	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_StaminaConsumed);

	MYFPS_DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StaminaRegen_CD);
};
